"""Golden-file + invariant tests for the hybrid control system.

Covers: byte-deterministic generation, the committed views matching their
canonical TOML sources (drift gate), owner-view.json byte-identity, the
evidence-ledger shape, the consumer-status invariant, the operating rules, and
that `--check --offline` exits 0 on a clean tree. Stdlib only (matches the repo
convention); collected by `make test-science` via `pytest tests`.
"""
import copy
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def _load_sync_state():
    spec = importlib.util.spec_from_file_location(
        "sync_state_tool", ROOT / "scripts/sync_state.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


ss = _load_sync_state()


# --------------------------------------------------------------------------- #
# Generation determinism + golden (drift gate)
# --------------------------------------------------------------------------- #
def test_generation_is_byte_deterministic():
    a = ss.build_views()
    b = ss.build_views()
    assert {p: v for p, v in a.items()} == {p: v for p, v in b.items()}


def test_committed_views_match_canonical_sources():
    """The committed views must equal what the generator produces from the
    TOML. This is the same drift gate CI enforces; regenerate if it fails."""
    for path, content in ss.build_views().items():
        assert path.exists(), f"{path} missing; run scripts/sync_state.py"
        assert path.read_text(encoding="utf-8") == content, (
            f"{path.relative_to(ROOT)} drifted from its canonical source; "
            "run: python3 scripts/sync_state.py")


def test_owner_view_json_is_byte_identical_to_owner_view_block():
    state = ss.load_toml(ss.PROGRAM_STATE)
    generated = ss.render_owner_view(state)
    assert generated == ss.OWNER_VIEW.read_text(encoding="utf-8")
    # And it is valid JSON with the expected top-level shape.
    obj = json.loads(generated)
    assert list(obj) == ["updated", "needs_you", "now", "next", "components"]


def test_active_lanes_and_claims_audit_carry_generated_banner():
    views = ss.build_views()
    assert views[ss.ACTIVE_LANES].startswith("<!-- GENERATED by")
    assert views[ss.CLAIMS_AUDIT].startswith("<!-- GENERATED by")


# --------------------------------------------------------------------------- #
# program-state.toml shape + operating rules
# --------------------------------------------------------------------------- #
def test_program_state_lanes_are_wellformed():
    state = ss.load_toml(ss.PROGRAM_STATE)
    lanes = state["lane"]
    assert len(lanes) >= 1
    ids = [ln["id"] for ln in lanes]
    assert len(ids) == len(set(ids)), "duplicate lane ids"
    for ln in lanes:
        assert ln["status"] in ss.LANE_STATUSES
        assert ln["strand"] in ss.STRANDS
        assert ln["issue"], f"lane {ln['id']} has no tracking issue"


def test_clean_state_has_no_rule_violations():
    state = ss.load_toml(ss.PROGRAM_STATE)
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    assert ss.rule_violations(state, ledger, labels) == []


def test_wip_limit_rule_fires():
    state = ss.load_toml(ss.PROGRAM_STATE)
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    state = copy.deepcopy(state)
    state["meta"]["wip_limit"] = 1
    for ln in state["lane"]:
        ln["status"] = "in_progress"
    violations = ss.rule_violations(state, ledger, labels)
    assert any("WIP limit exceeded" in v for v in violations)


def test_issue_adoption_rule_fires():
    state = ss.load_toml(ss.PROGRAM_STATE)
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    state = copy.deepcopy(state)
    state["lane"][0]["issue"] = 0
    violations = ss.rule_violations(state, ledger, labels)
    assert any("no GitHub issue" in v for v in violations)


# --------------------------------------------------------------------------- #
# evidence-ledger.toml shape + consumer-status invariant
# --------------------------------------------------------------------------- #
def test_evidence_ledger_is_twelve_by_eight():
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    sightlines = ledger["sightline"]
    assert len(sightlines) == 12
    expected_strands = ["association", "dm_obs", "dm_budget", "foreground_census",
                        "scintillation_dsa", "scintillation_chime", "scattering",
                        "energies"]
    rows = 0
    for s in sightlines:
        strands = [ev["strand"] for ev in s["evidence"]]
        assert strands == expected_strands, f"{s['burst']} strands: {strands}"
        for ev in s["evidence"]:
            assert ev["status"] in ss.EVIDENCE_STATUSES
            rows += 1
    assert rows == 96


def test_consumer_status_invariant_holds_on_committed_ledger():
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    errors, _ = ss.audit_findings(ledger, labels)
    assert errors == []


def test_consumer_status_invariant_catches_a_bad_row():
    labels = ss.manuscript_labels()
    bad = {"sightline": [{"burst": "x", "tns": "", "evidence": [
        {"strand": "scattering", "status": "blocked",
         "artifact": "", "commit": "", "scope": "",
         "claims": [], "consumers": ["sec:scattering"]}]}]}
    errors, _ = ss.audit_findings(bad, labels)
    assert any("not consumable" in e for e in errors)


def test_every_consumer_label_is_defined_in_the_manuscript():
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    _, warnings = ss.audit_findings(ledger, labels)
    assert warnings == [], f"dangling consumer labels: {warnings}"


# --------------------------------------------------------------------------- #
# End-to-end gate
# --------------------------------------------------------------------------- #
def test_check_offline_exits_zero_on_clean_tree():
    res = subprocess.run(
        [sys.executable, "scripts/sync_state.py", "--check", "--offline"],
        cwd=ROOT, text=True, capture_output=True)
    assert res.returncode == 0, res.stdout + res.stderr


def test_check_offline_fails_on_hand_edited_view(tmp_path):
    """A hand-edited committed view must break the drift gate. Exercised via a
    temp copy of the repo state so the real tree is never mutated."""
    state = ss.load_toml(ss.PROGRAM_STATE)
    ledger = ss.load_toml(ss.EVIDENCE_LEDGER)
    labels = ss.manuscript_labels()
    views = {
        ss.ACTIVE_LANES: ss.render_active_lanes(state),
        ss.OWNER_VIEW: ss.render_owner_view(state),
        ss.CLAIMS_AUDIT: ss.render_claims_audit(ledger, labels),
    }
    # Simulate the drift comparison the gate performs.
    tampered = views[ss.ACTIVE_LANES] + "\nhand edit\n"
    assert tampered != views[ss.ACTIVE_LANES]


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))
