#!/usr/bin/env python
"""Generate sample_table.tex (Table 1: the co-detection sample roster).

Reads only trust-safe raw observational inputs from the pinned dsa110-FLITS
submodule and emits an AASTeX deluxetable. Per CONTEXT.md's trust reset,
per-burst designations, epochs, and sky positions are raw inputs (not revoked),
whereas DM_obs, TOA residuals, chance-coincidence probabilities, and association
verdicts are Wave-3 revoked pending V6 -- those columns are intentionally
omitted here.

Sources (pinned submodule pipeline/):
  - configs/bursts.yaml                      -> MJD, UTC, RA/Dec (source of truth)
  - scattering/scat_analysis/burst_metadata.py::_FALLBACK_TNS  -> nickname -> TNS

Regenerate with:  python scripts/make_sample_table.py
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
PIPELINE = REPO / "pipeline"
REGISTRY = PIPELINE / "configs" / "bursts.yaml"
META = PIPELINE / "scattering" / "scat_analysis" / "burst_metadata.py"
OUT = REPO / "sample_table.tex"


def _pinned_commit() -> str:
    head = (PIPELINE / ".git").read_text().strip() if (PIPELINE / ".git").is_file() else ""
    # submodule .git is a gitdir pointer; read the actual HEAD sha from the superproject
    import subprocess

    try:
        sha = subprocess.check_output(
            ["git", "-C", str(PIPELINE), "rev-parse", "--short", "HEAD"], text=True
        ).strip()
        return sha
    except Exception:
        return "unknown"


def _load_tns_map() -> dict[str, str]:
    spec = importlib.util.spec_from_file_location("burst_metadata", META)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return {k.lower(): v for k, v in mod._FALLBACK_TNS.items()}


def main() -> None:
    registry = yaml.safe_load(REGISTRY.read_text())["bursts"]
    tns = _load_tns_map()
    commit = _pinned_commit()

    rows = []
    for nick, rec in registry.items():
        rows.append(
            {
                "tns": tns.get(nick.lower(), nick.upper()),
                "nick": nick,
                "ra": rec["ra_deg"],
                "dec": rec["dec_deg"],
                "mjd": rec["mjd"],
                "utc": rec["utc"].replace("T", " "),
            }
        )
    rows.sort(key=lambda r: r["mjd"])  # chronological

    body = []
    for r in rows:
        body.append(
            f"{r['tns']} & \\textit{{{r['nick']}}} & "
            f"${r['ra']:.4f}$ & ${r['dec']:+.4f}$ & "
            f"${r['mjd']:.3f}$ & {r['utc']} \\\\"
        )

    tex = f"""% Rows generated by scripts/make_sample_table.py from the pinned dsa110-FLITS
% submodule (pipeline/, commit {commit}): configs/bursts.yaml (MJD/UTC/RA/Dec,
% source of truth) and scattering/scat_analysis/burst_metadata.py::_FALLBACK_TNS
% (nickname -> TNS). Trust-safe columns only -- designations, epochs, and sky
% positions are raw observational inputs (CONTEXT.md trust reset). DM_obs, TOA
% residuals, chance-coincidence probabilities, and association verdicts are
% Wave-3 revoked and intentionally excluded pending V6. Do not hand-edit;
% regenerate with: python scripts/make_sample_table.py
\\begin{{deluxetable*}}{{llcccc}}
\\tablecaption{{The CHIME/FRB--DSA-110 co-detection sample: twelve fast radio
bursts detected by both facilities between 2022 February and 2024 February.
Columns list the TNS designation, the internal nickname used throughout this
paper, the J2000 sky position (decimal degrees), and the burst detection epoch
(MJD and UTC, referenced to 400\\,MHz). This table lists only the raw
observational identification of the sample; the association diagnostics---per-burst
$\\mathrm{{DM}}_{{\\mathrm{{obs}}}}$, timing residuals, and chance-coincidence
probabilities---are withheld pending the Section~\\ref{{sec:toa}} re-validation
(V6). \\label{{tab:sample}}}}
\\tablehead{{\\colhead{{TNS}} & \\colhead{{Nickname}} & \\colhead{{R.A.}} &
  \\colhead{{Decl.}} & \\colhead{{MJD}} & \\colhead{{UTC}}}}
\\startdata
{chr(10).join(body)}
\\enddata
\\end{{deluxetable*}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} rows, pinned commit {commit})")


if __name__ == "__main__":
    main()
