#!/usr/bin/env python
"""Generate sample_table.tex (Table 1: the co-detection sample roster).

Reads trust-safe raw observational inputs plus V6-revalidated association
diagnostics from the pinned dsa110-FLITS submodule and emits an AASTeX
deluxetable.

Sources (pinned submodule pipeline/):
  - configs/bursts.yaml                       -> MJD, UTC, RA/Dec
  - scattering/scat_analysis/burst_metadata.py::_FALLBACK_TNS -> nickname -> TNS
  - crossmatching/toa_crossmatch_results.json -> shared-DM timing residuals
  - crossmatching/association_report.json     -> P_cc and association verdict inputs

Regenerate with: python scripts/make_sample_table.py
For an isolated FLITS worktree, set FABER2026_PIPELINE_SOURCE=/path/to/worktree.
"""
from __future__ import annotations

import importlib.util
import json
import math
import os
import subprocess
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
PIPELINE = REPO / "pipeline"
PIPELINE_SOURCE = Path(os.environ.get("FABER2026_PIPELINE_SOURCE", PIPELINE))
REGISTRY = PIPELINE_SOURCE / "configs" / "bursts.yaml"
META = PIPELINE_SOURCE / "scattering" / "scat_analysis" / "burst_metadata.py"
TOA_RESULTS = PIPELINE_SOURCE / "crossmatching" / "toa_crossmatch_results.json"
ASSOCIATION_REPORT = PIPELINE_SOURCE / "crossmatching" / "association_report.json"
OUT = REPO / "sample_table.tex"


def _source_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(PIPELINE_SOURCE), "rev-parse", "--short", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def _load_tns_map() -> dict[str, str]:
    spec = importlib.util.spec_from_file_location("burst_metadata", META)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return {k.lower(): v for k, v in mod._FALLBACK_TNS.items()}


def _tex_scientific(value: float) -> str:
    exponent = math.floor(math.log10(value))
    mantissa = value / 10**exponent
    return rf"${mantissa:.1f}\times10^{{{exponent}}}$"


def _association_verdict(row: dict) -> str:
    pcc_ok = row["chance_coincidence_P"] < 1e-3
    pos_ok = row["position"]["consistent"] is True
    dm_ok = row["dm_agreement"]["consistent"]
    if pcc_ok and pos_ok and dm_ok is True:
        return "assoc. (DM+pos.)"
    if pcc_ok and pos_ok and dm_ok is None:
        return "assoc. (pos.)"
    return "review"


def _load_association_diagnostics() -> dict[str, dict[str, str]]:
    toa = {k.lower(): v for k, v in json.loads(TOA_RESULTS.read_text()).items()}
    assoc = {
        row["name"].lower(): row
        for row in json.loads(ASSOCIATION_REPORT.read_text())["bursts"]
    }
    diagnostics = {}
    for nick, assoc_row in assoc.items():
        toa_row = toa[nick]
        residual_ms = toa_row["measured_offset_ms"] - toa_row["geometric_delay_ms"]
        diagnostics[nick] = {
            "toa_residual_ms": f"${residual_ms:+.2f}$",
            "pcc": _tex_scientific(assoc_row["chance_coincidence_P"]),
            "verdict": _association_verdict(assoc_row),
        }
    return diagnostics


def main() -> None:
    registry = yaml.safe_load(REGISTRY.read_text())["bursts"]
    tns = _load_tns_map()
    diagnostics = _load_association_diagnostics()
    commit = _source_commit()

    rows = []
    for nick, rec in registry.items():
        diag = diagnostics[nick.lower()]
        rows.append(
            {
                "tns": tns.get(nick.lower(), nick.upper()),
                "nick": nick,
                "ra": rec["ra_deg"],
                "dec": rec["dec_deg"],
                "mjd": rec["mjd"],
                "utc": rec["utc"].replace("T", " "),
                **diag,
            }
        )
    rows.sort(key=lambda r: r["mjd"])

    body = []
    for r in rows:
        body.append(
            f"{r['tns']} & "
            f"${r['ra']:.4f}$ & ${r['dec']:+.4f}$ & "
            f"${r['mjd']:.3f}$ & {r['utc']} & "
            f"{r['toa_residual_ms']} & {r['pcc']} & {r['verdict']} \\\\"
        )

    tex = f"""% Rows generated by scripts/make_sample_table.py from dsa110-FLITS
% source commit {commit}: configs/bursts.yaml (MJD/UTC/RA/Dec), burst_metadata.py
% (nickname -> TNS), crossmatching/toa_crossmatch_results.json (shared-DSA-DM
% TOA residuals), and crossmatching/association_report.json (P_cc/verdict).
% V6 restored the association diagnostics under the shared DSA-DM reference.
% Do not hand-edit; regenerate with: python scripts/make_sample_table.py
\\begin{{deluxetable*}}{{lccccccc}}
\\tablecaption{{The CHIME/FRB--DSA-110 co-detection sample: twelve fast radio
bursts detected by both facilities between 2022 February and 2024 February.
Columns list the TNS designation, J2000 sky position (decimal degrees), burst
detection epoch (MJD and UTC, referenced to 400\\,MHz), and the
Section~\\ref{{sec:toa}} association diagnostics restored by V6: the shared-DSA-DM
timing residual $\\Delta t$, chance-coincidence probability $P_{{\\rm cc}}$, and
association verdict. The residual carries a per-burst systematic of
$\\sim\\!1$\\,ms (inter-site clock alignment) plus a convention-dependent
DM-reference term; its sign convention and the acceptance criterion are defined
in Section~\\ref{{sec:toa}}. \\label{{tab:sample}}}}
\\tabletypesize{{\\scriptsize}}
\\tablehead{{\\colhead{{TNS}} & \\colhead{{R.A.}} &
  \\colhead{{Decl.}} & \\colhead{{MJD}} & \\colhead{{UTC}} &
  \\colhead{{$\\Delta t$ (ms)}} & \\colhead{{$P_{{\\rm cc}}$}} &
  \\colhead{{Verdict}}}}
\\startdata
{chr(10).join(body)}
\\enddata
\\end{{deluxetable*}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT.relative_to(REPO)} ({len(rows)} rows, source commit {commit})")


if __name__ == "__main__":
    main()
