#!/usr/bin/env python3
"""Hybrid control-system generator: canonical state -> derived views + drift gate.

Design: docs/rse/specs/plan/plan-hybrid-control-system.md.

State is split by who can know it:

* Fetched live, never stored -- PR/issue/branch/CI state. Queried from `gh` only
  in `--check` (drop `--offline`) to flag stored<->live contradictions. It is
  never baked into the generated files, so the outputs stay byte-deterministic
  and CI's `--check --offline` is a true drift gate.
* Stored canonically -- docs/rse/control/program-state.toml (lanes + owner-view) and
  docs/rse/control/evidence-ledger.toml (12 sightlines x 8 strands). GitHub cannot know
  scientific trust status, gates, next actions, or the lane->issue association.

Outputs (regenerated from the two TOML files alone):

1. docs/rse/control/ACTIVE_LANES.md        -- lane table (GENERATED banner).
2. docs/rse/control/board/owner-view.json  -- byte-identical to the owner_view block;
                                      JSON carries no comment, so no banner line
                                      (its provenance lives in program-state.toml).
                                      scripts/render_journal_panel.py bakes it
                                      into readiness.html unchanged.
3. docs/rse/control/board/claims-audit.md  -- the ledger's consumer (GENERATED banner),
                                      cross-checked against manuscript labels.

Usage:
    python3 scripts/sync_state.py                 # write the three views
    python3 scripts/sync_state.py --check         # gate: drift + rules + live
    python3 scripts/sync_state.py --check --offline  # gate without gh (CI)
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROGRAM_STATE = ROOT / "docs/rse/control/program-state.toml"
EVIDENCE_LEDGER = ROOT / "docs/rse/control/evidence-ledger.toml"
ACTIVE_LANES = ROOT / "docs/rse/control/ACTIVE_LANES.md"
OWNER_VIEW = ROOT / "docs/rse/control/board/owner-view.json"
CLAIMS_AUDIT = ROOT / "docs/rse/control/board/claims-audit.md"

REPO = "jakobtfaber/Faber2026"
ISSUE_URL = "https://github.com/" + REPO + "/issues/{n}"
PR_URL = "https://github.com/" + REPO + "/pull/{n}"

LANE_STATUSES = {"proposed", "in_progress", "blocked", "needs_owner",
                 "documented_fail", "done"}
TERMINAL_LANE_STATUSES = {"done", "documented_fail"}
STRANDS = {"association", "budget_census", "scattering", "scintillation",
           "energies", "synthesis", "mechanics"}
EVIDENCE_STATUSES = {"trusted", "diagnostic", "upper_limit", "unavailable",
                     "blocked", "documented_fail"}
# Only these evidence statuses may be consumed by a manuscript label.
CONSUMABLE = {"trusted", "upper_limit", "documented_fail"}

BANNER = ("<!-- GENERATED by scripts/sync_state.py from {src} -- do not "
          "hand-edit. -->\n<!-- Edit {src} and run: python3 "
          "scripts/sync_state.py -->\n")


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def load_toml(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def manuscript_labels() -> set[str]:
    """Every \\label{} defined in main.tex and sections/*.tex (deterministic)."""
    labels: set[str] = set()
    files = [ROOT / "main.tex"] + sorted((ROOT / "sections").glob("*.tex"))
    pat = re.compile(r"\\label\{([^}]+)\}")
    for f in files:
        if f.exists():
            labels.update(pat.findall(f.read_text(encoding="utf-8")))
    return labels


# --------------------------------------------------------------------------- #
# View 1: ACTIVE_LANES.md
# --------------------------------------------------------------------------- #
def cell(s: str) -> str:
    return str(s).replace("|", "\\|")


def render_active_lanes(state: dict) -> str:
    meta = state.get("meta", {})
    lanes = state.get("lane", [])
    updated = meta.get("updated", "?")
    wip_limit = meta.get("wip_limit", 0)
    in_flight = sum(1 for ln in lanes if ln.get("status") == "in_progress")

    out = [BANNER.format(src="docs/rse/control/program-state.toml")]
    out.append("# Active lanes\n")
    out.append(
        "Operational control surface for Faber2026, generated from "
        "`docs/rse/control/program-state.toml`. One row per lane. Live PR/issue/branch "
        "state is verified by `scripts/sync_state.py --check` (advisory), not "
        "baked into this table.\n")
    out.append(
        "> **Frozen / not the frontier.** Decision and execution frontier is "
        "`docs/rse/control/BOARD.md` + `docs/rse/wayfinder/` tickets. This table "
        "and `program-state.toml` are retained for the CI `check-state` gate "
        "only; do not treat lane rows here as current work ordering.\n")
    out.append(
        "**Updated:** {u} · **WIP limit:** {w} · "
        "**In flight:** {n}/{w}\n".format(u=updated, w=wip_limit, n=in_flight))

    out.append("| Lane | Title | Strand | Status | Owner | Issue | Branch "
               "| PR | Needs owner | Next action |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for ln in lanes:
        issue = ln.get("issue", 0)
        issue_cell = ("[#{n}]({u})".format(n=issue, u=ISSUE_URL.format(n=issue))
                      if issue else "—")
        pr = ln.get("pr", 0)
        pr_cell = ("[#{n}]({u})".format(n=pr, u=PR_URL.format(n=pr))
                   if pr else "—")
        branch = ln.get("branch") or "—"
        owner = ln.get("owner") or "—"
        needs = "yes" if ln.get("needs_owner") else "no"
        out.append("| `{id}` | {title} | {strand} | {status} | {owner} | "
                   "{issue} | {branch} | {pr} | {needs} | {nxt} |".format(
                       id=cell(ln.get("id", "")),
                       title=cell(ln.get("title", "")),
                       strand=cell(ln.get("strand", "")),
                       status=cell(ln.get("status", "")),
                       owner=cell(owner),
                       issue=issue_cell,
                       branch="`{}`".format(cell(branch)) if branch != "—"
                       else "—",
                       pr=pr_cell,
                       needs=needs,
                       nxt=cell(ln.get("next_action", ""))))

    out.append("\n## Gates per lane\n")
    for ln in lanes:
        gates = ln.get("gates", [])
        gate_txt = "; ".join(gates) if gates else "_none recorded_"
        out.append("- **`{id}`** — {g}".format(
            id=ln.get("id", ""), g=gate_txt))
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# View 2: owner-view.json (byte-identical to the [owner_view] block)
# --------------------------------------------------------------------------- #
def render_owner_view(state: dict) -> str:
    ov = state["owner_view"]
    obj: dict = {"updated": ov["updated"]}
    for key in ("needs_you", "now", "next"):
        items = []
        for it in ov.get(key, []):
            d = {}
            for field in ("h", "d", "who"):
                if field in it:
                    d[field] = it[field]
            items.append(d)
        obj[key] = items
    comps = []
    for c in ov.get("component", []):
        d = {}
        for field in ("name", "lane", "status", "status_class", "next"):
            if field in c:
                d[field] = c[field]
        comps.append(d)
    obj["components"] = comps
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


# --------------------------------------------------------------------------- #
# View 3: claims-audit.md (+ manuscript cross-check)
# --------------------------------------------------------------------------- #
def audit_findings(ledger: dict, labels: set[str]) -> tuple[list[str], list[str]]:
    """Return (errors, warnings). Errors fail --check; warnings do not."""
    errors: list[str] = []
    warnings: list[str] = []
    for s in ledger.get("sightline", []):
        burst = s.get("burst", "?")
        for ev in s.get("evidence", []):
            strand = ev.get("strand", "?")
            status = ev.get("status", "?")
            consumers = ev.get("consumers", [])
            if consumers and status not in CONSUMABLE:
                errors.append(
                    "{b} · {s}: status '{st}' is not consumable, but "
                    "manuscript labels consume it: {c}".format(
                        b=burst, s=strand, st=status, c=", ".join(consumers)))
            for label in consumers:
                if label not in labels:
                    warnings.append(
                        "{b} · {s}: consumer label '{l}' is not defined "
                        "in the manuscript".format(b=burst, s=strand, l=label))
    return errors, warnings


def render_claims_audit(ledger: dict, labels: set[str]) -> str:
    sightlines = ledger.get("sightline", [])
    rows = [(s.get("burst", "?"), s.get("tns", ""), ev)
            for s in sightlines for ev in s.get("evidence", [])]
    errors, warnings = audit_findings(ledger, labels)

    status_counts: dict[str, int] = {}
    for _, _, ev in rows:
        status_counts[ev.get("status", "?")] = \
            status_counts.get(ev.get("status", "?"), 0) + 1

    out = [BANNER.format(src="docs/rse/control/evidence-ledger.toml")]
    out.append("# Claims audit\n")
    out.append(
        "Generated from `docs/rse/control/evidence-ledger.toml`, cross-checked against "
        "`\\label{}`s in `main.tex` and `sections/*.tex`. A manuscript label may "
        "consume only `trusted`, `upper_limit`, or `documented_fail` evidence; "
        "anything else is an error.\n")
    out.append(
        "**Sightlines:** {ns} · **Evidence rows:** {nr} · "
        "**Errors:** {ne} · **Warnings:** {nw}\n".format(
            ns=len(sightlines), nr=len(rows), ne=len(errors), nw=len(warnings)))

    out.append("**Status totals:** " + " · ".join(
        "{k} {v}".format(k=k, v=status_counts[k])
        for k in sorted(status_counts)) + "\n")

    out.append("## Cross-check findings\n")
    if not errors and not warnings:
        out.append("_No errors or warnings: every consumed evidence row is "
                   "consumable and every consumer label is defined._\n")
    else:
        for e in errors:
            out.append("- **ERROR** — " + e)
        for w in warnings:
            out.append("- **warning** — " + w)
        out.append("")

    out.append("## Reported claims (evidence the manuscript consumes)\n")
    out.append("Only rows with manuscript consumers appear here.\n")
    any_reported = False
    for burst, tns, ev in rows:
        if not ev.get("consumers"):
            continue
        any_reported = True
        out.append("### {b} · {s} — `{st}`".format(
            b=burst, s=ev.get("strand"), st=ev.get("status")))
        art = ev.get("artifact") or "—"
        commit = ev.get("commit") or "—"
        out.append("- artifact: `{a}` @ `{c}`".format(a=art, c=commit))
        out.append("- consumers: " + ", ".join(
            "`{}`".format(x) for x in ev["consumers"]))
        for claim in ev.get("claims", []):
            out.append("- claim: {}".format(claim))
        out.append("")
    if not any_reported:
        out.append("_No evidence rows currently carry manuscript consumers._\n")

    out.append("## Full ledger (12 sightlines × 8 strands)\n")
    for s in sightlines:
        out.append("### {b} ({tns})".format(
            b=s.get("burst"), tns=s.get("tns", "")))
        out.append("| strand | status | consumers | scope |")
        out.append("|---|---|---|---|")
        for ev in s.get("evidence", []):
            cons = ", ".join("`{}`".format(x) for x in ev.get("consumers", [])) \
                or "—"
            out.append("| {strand} | {status} | {cons} | {scope} |".format(
                strand=cell(ev.get("strand", "")),
                status=cell(ev.get("status", "")),
                cons=cell(cons),
                scope=cell(ev.get("scope", ""))))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------- #
# Rules (structural + operating; run in --check, offline-safe)
# --------------------------------------------------------------------------- #
def rule_violations(state: dict, ledger: dict, labels: set[str]) -> list[str]:
    errors: list[str] = []
    meta = state.get("meta", {})
    lanes = state.get("lane", [])
    wip_limit = meta.get("wip_limit", 0)

    seen_ids: set[str] = set()
    in_flight = 0
    for ln in lanes:
        lid = ln.get("id", "")
        if not lid:
            errors.append("lane with an empty id")
        if lid in seen_ids:
            errors.append("duplicate lane id '{}'".format(lid))
        seen_ids.add(lid)
        if ln.get("status") not in LANE_STATUSES:
            errors.append("lane '{}' has invalid status '{}'".format(
                lid, ln.get("status")))
        if ln.get("strand") not in STRANDS:
            errors.append("lane '{}' has invalid strand '{}'".format(
                lid, ln.get("strand")))
        if not ln.get("issue"):
            errors.append("lane '{}' has no GitHub issue (issue adoption "
                          "landed; every lane needs a tracking issue)".format(lid))
        if ln.get("status") == "in_progress":
            in_flight += 1
    if in_flight > wip_limit:
        errors.append("WIP limit exceeded: {n} lanes in_progress > wip_limit "
                      "{w}".format(n=in_flight, w=wip_limit))

    # Evidence ledger structural + consumer-status invariant.
    for s in ledger.get("sightline", []):
        burst = s.get("burst", "?")
        for ev in s.get("evidence", []):
            if ev.get("status") not in EVIDENCE_STATUSES:
                errors.append("evidence {b}/{s} has invalid status '{st}'".format(
                    b=burst, s=ev.get("strand"), st=ev.get("status")))
    audit_errors, _ = audit_findings(ledger, labels)
    errors.extend(audit_errors)
    return errors


# --------------------------------------------------------------------------- #
# Live GitHub contradiction checks (skipped with --offline)
# --------------------------------------------------------------------------- #
def gh_json(args: list[str]):
    try:
        res = subprocess.run(["gh", *args], capture_output=True, text=True,
                             timeout=30)
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return None, "gh unavailable: {}".format(exc)
    if res.returncode != 0:
        return None, res.stderr.strip()
    try:
        return json.loads(res.stdout), None
    except json.JSONDecodeError as exc:
        return None, "gh returned non-JSON: {}".format(exc)


def live_contradictions(state: dict) -> tuple[list[str], list[str]]:
    """Return (contradictions, advisories). Contradictions fail --check."""
    contradictions: list[str] = []
    advisories: list[str] = []
    for ln in state.get("lane", []):
        lid = ln.get("id", "")
        status = ln.get("status")
        pr = ln.get("pr", 0)
        issue = ln.get("issue", 0)
        worktree = ln.get("worktree", "")

        if pr:
            data, err = gh_json(["pr", "view", str(pr), "--repo", REPO,
                                  "--json", "state,mergedAt"])
            if err:
                advisories.append("lane '{}' PR #{}: {}".format(lid, pr, err))
            elif data and data.get("mergedAt") and \
                    status not in TERMINAL_LANE_STATUSES:
                contradictions.append(
                    "lane '{}' PR #{} is MERGED but lane status is '{}' "
                    "(non-terminal)".format(lid, pr, status))
        if issue:
            data, err = gh_json(["issue", "view", str(issue), "--repo", REPO,
                                 "--json", "state"])
            if err:
                advisories.append("lane '{}' issue #{}: {}".format(lid, issue, err))
            elif data and data.get("state") == "CLOSED" and \
                    status not in TERMINAL_LANE_STATUSES:
                contradictions.append(
                    "lane '{}' issue #{} is CLOSED but lane status is '{}' "
                    "(non-terminal)".format(lid, issue, status))
        if worktree:
            wt = Path(worktree).expanduser()
            if not wt.exists():
                contradictions.append(
                    "lane '{}' worktree does not exist: {}".format(lid, worktree))
    return contradictions, advisories


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def build_views() -> dict[Path, str]:
    state = load_toml(PROGRAM_STATE)
    ledger = load_toml(EVIDENCE_LEDGER)
    labels = manuscript_labels()
    return {
        ACTIVE_LANES: render_active_lanes(state),
        OWNER_VIEW: render_owner_view(state),
        CLAIMS_AUDIT: render_claims_audit(ledger, labels),
    }


def cmd_generate() -> int:
    for path, content in build_views().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print("wrote {}".format(path.relative_to(ROOT)))
    return 0


def cmd_check(offline: bool) -> int:
    state = load_toml(PROGRAM_STATE)
    ledger = load_toml(EVIDENCE_LEDGER)
    labels = manuscript_labels()
    views = {
        ACTIVE_LANES: render_active_lanes(state),
        OWNER_VIEW: render_owner_view(state),
        CLAIMS_AUDIT: render_claims_audit(ledger, labels),
    }

    failed = False

    # (1) Drift gate: regenerated views must match committed byte-for-byte.
    for path, content in views.items():
        rel = path.relative_to(ROOT)
        if not path.exists():
            print("DRIFT: {} does not exist (run sync_state.py)".format(rel))
            failed = True
        elif path.read_text(encoding="utf-8") != content:
            print("DRIFT: {} differs from program-state.toml/evidence-ledger."
                  "toml (regenerate; do not hand-edit)".format(rel))
            failed = True
    if not failed:
        print("drift: 3/3 views match their canonical sources")

    # (2) Operating rules (offline-safe).
    errors = rule_violations(state, ledger, labels)
    if errors:
        failed = True
        for e in errors:
            print("RULE: {}".format(e))
    else:
        print("rules: all lane/ledger operating rules pass")

    # (2b) Warnings from the manuscript cross-check (non-fatal).
    _, warnings = audit_findings(ledger, labels)
    for w in warnings:
        print("warning: {}".format(w))

    # (3) Live stored<->live contradiction checks.
    if offline:
        print("live: skipped (--offline)")
    else:
        contradictions, advisories = live_contradictions(state)
        for a in advisories:
            print("advisory: {}".format(a))
        if contradictions:
            failed = True
            for c in contradictions:
                print("CONTRADICTION: {}".format(c))
        else:
            print("live: no stored<->live contradictions")

    if failed:
        print("\n--check FAILED")
        return 1
    print("\n--check PASSED")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="gate: verify views match sources; do not write")
    ap.add_argument("--offline", action="store_true",
                    help="skip live gh queries (structure/drift/rules only)")
    args = ap.parse_args(argv)
    if args.check:
        return cmd_check(args.offline)
    return cmd_generate()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
